name: fastmac
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # 给脚本加上执行权限
      - name: chmod script
        run: chmod +x script-mac.sh

      - name: run mac script
        run: ./script-mac.sh
