name: fastmac
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 360
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: chmod script
        run: chmod +x script-mac.sh

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        id: tmate
        with:
          detached: true

      - name: run mac script
        run: ./script-mac.sh
        env:
          TMATE_SSH: ${{ steps.tmate.outputs['ssh-command'] }}
          TMATE_WEB_URL: ${{ steps.tmate.outputs['web-url'] }}

      - name: keep session alive
        run: sleep 15s
